name: Build Meilisearch v1.19.1 on Rocky Linux 9

on:
  workflow_dispatch:
    inputs:
      action:
        description: '触发类型'
        required: true
        default: 'build'
        enum: [build]

jobs:
  build-meilisearch:
    name: 编译 Meilisearch v1.19.1（Rocky Linux 9）
    container:
      image: litmusimage/rockylinux:9
    runs-on: ubuntu-latest

    steps:
      - name: 安装系统依赖（含 git）
        run: |
          yum update -y
          yum install -y \
            git \  # 确保 git 在此步骤安装
            curl \
            gcc \
            make \
            cmake3 \
            openssl-devel \
            zlib-devel \
            pkgconfig \
            which
          sudo ln -sf /usr/bin/cmake3 /usr/bin/cmake

      - name: 验证容器环境（含 git 检查）
        run: |
          # 先检查基础工具（此时 git 已安装）
          ldd --version  # 验证 GLIBC 版本
          git --version  # 现在 git 已安装，不会报错
          curl --version
          gcc --version

      - name: 安装 Rust 工具链
        uses: dtolnay/rust-toolchain@1.85
        with:
          toolchain: stable
          override: true
          components: rust-src, cargo, rustc-dev

      - name: 克隆并检出源码
        run: |
          git clone https://github.com/meilisearch/meilisearch.git  # git 已安装，可正常执行
          cd meilisearch
          git checkout tags/v1.19.1

      - name: 配置编译环境
        run: |
          cd meilisearch
          export TARGET=x86_64-unknown-linux-gnu

      - name: 编译发布版
        run: |
          cd meilisearch
          cargo build --release --locked

      - name: 验证 GLIBC 依赖
        run: |
          cd meilisearch/target/release
          ldd meilisearch | grep GLIBC_

      - name: 保存编译产物（upload-artifact@v4）
        uses: actions/upload-artifact@v4
        with:
          name: meilisearch-v1.19.1-linux-amd64-rocky9
          path: meilisearch/target/release/meilisearch
          retention-days: 7
