name: Build Meilisearch v1.19.1 on Rocky Linux 9

on:
  workflow_dispatch:
    inputs:
      action:
        description: '触发类型（仅 build）'
        required: true
        default: 'build'
        enum: [build]

jobs:
  build-meilisearch:
    name: 编译 Meilisearch v1.19.1（Rocky Linux 9）
    container:
      image: rockylinux/rockylinux:9
    runs-on: ubuntu-latest

    steps:
      ###########################
      # 步骤 1：安装基础工具（含 bash、curl、wget）
      ###########################
      - name: 安装基础工具（关键）
        run: |
          # 更新系统包索引
          yum update -y
          
          # 安装 bash（最小化镜像可能未预装）
          yum install -y bash
          
          # 安装 curl（用于下载文件）
          yum install -y wget
          
          # 安装其他编译必需工具
          yum install -y \
            git \
            gcc \
            make \
            cmake3 \
            openssl-devel \
            zlib-devel \
            which \
            pkgconf-pkg-config \
            yum-utils  # 包含 yum-config-manager

      ###########################
      # 步骤 2：验证 bash 可用性
      ###########################
      - name: 验证 bash 安装
        run: |
          # 检查 bash 路径（应输出 /usr/bin/bash）
          which bash
          
          # 检查 PATH 环境变量（应包含 /usr/bin）
          echo "PATH: $PATH"

      ###########################
      # 步骤 3：安装 Rust 工具链（强制非交互式 + CI 环境）
      ###########################
      - name: 安装 Rust 工具链（rustup）
        run: |
          # 设置 CI 环境变量（告知 rustup 处于非交互式环境）
          export CI=true
          
          # 手动下载 rustup 安装脚本（避免 curl 管道符参数丢失）
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
          
         

          # 清理安装脚本（可选）
          rm -f rustup-installer.sh

          # 验证 cargo 是否安装成功（输出版本信息）
          cargo --version

      ###########################
      # 步骤 4：配置 cargo 路径（可选，若自动配置失败）
      ###########################
      - name: 配置 cargo 路径
        run: |
          # 将 cargo 加入 PATH（rustup 通常自动配置，若失败则手动添加）
          echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc

      ###########################
      # 步骤 5：安装 EPEL 仓库（依赖 curl/wget）
      ###########################
      - name: 安装 EPEL 仓库
        run: |
          # 下载 EPEL 9 最新仓库包
          wget -q https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
          
          # 安装 EPEL 仓库
          yum install -y ./epel-release-latest-9.noarch.rpm

      ###########################
      # 步骤 6：启用 EPEL 仓库并安装 pkgconf-pkg-config
      ###########################
      - name: 启用 EPEL 仓库并安装 pkgconf-pkg-config
        run: |
          # 启用 EPEL 仓库
          yum-config-manager --set-enabled epel
          
          # 安装 pkgconf-pkg-config（提供兼容的 pkg-config 工具）
          yum install -y pkgconf-pkg-config

      ###########################
      # 步骤 7：克隆并编译 Meilisearch 源码
      ###########################
      - name: 克隆并检出源码
        run: |
          git clone https://github.com/meilisearch/meilisearch.git
          cd meilisearch
          git checkout tags/v1.19.1

      - name: 配置编译环境
        run: |
          cd meilisearch
          export TARGET=x86_64-unknown-linux-gnu

      - name: 编译发布版
        run: |
          cd meilisearch
          cargo build --release --locked

      ###########################
      # 步骤 8：验证 GLIBC 依赖
      ###########################
      - name: 验证 GLIBC 依赖
        run: |
          cd meilisearch/target/release
          ldd meilisearch | grep GLIBC_

      ###########################
      # 步骤 9：保存编译产物
      ###########################
      - name: 保存编译产物
        uses: actions/upload-artifact@v4
        with:
          name: meilisearch-v1.19.1-linux-amd64-rocky9
          path: meilisearch/target/release/meilisearch
          retention-days: 7
