name: Build Meilisearch v1.19.1 on Rocky Linux 9

on:
  workflow_dispatch:
    inputs:
      action:
        description: '触发类型'
        required: true
        default: 'build'
        enum: [build]

jobs:
  build-meilisearch:
    name: 编译 Meilisearch v1.19.1（Rocky Linux 9）
    container:
      image: litmusimage/rockylinux:9
    runs-on: ubuntu-latest

    steps:
      - name: 安装系统依赖（含 yum-utils）
        run: |
          yum update -y
          # 安装 yum-utils（包含 yum-config-manager）
          yum install -y yum-utils
          # 安装其他必要依赖
          yum install -y \
            git \
            curl \
            gcc \
            make \
            cmake3 \
            openssl-devel \
            zlib-devel \
            pkgconf-pkg-config \
            which

      - name: 启用 EPEL 仓库（可选，若需额外包）
        run: |
          # 使用 yum-config-manager 启用 EPEL 仓库（现在工具已可用）
          yum-config-manager --set-enabled epel

      - name: 验证环境
        run: |
          ldd --version
          git --version
          pkg-config --version
          cmake --version
          openssl version
          # 验证 yum-config-manager 可用
          yum-config-manager --list | head  # 输出仓库列表，确认工具正常

      - name: 安装 Rust 工具链
        uses: dtolnay/rust-toolchain@1.85
        with:
          toolchain: stable
          override: true
          components: rust-src, cargo, rustc-dev

      - name: 克隆并检出源码
        run: |
          git clone https://github.com/meilisearch/meilisearch.git
          cd meilisearch
          git checkout tags/v1.19.1

      - name: 配置编译环境
        run: |
          cd meilisearch
          export TARGET=x86_64-unknown-linux-gnu

      - name: 编译发布版
        run: |
          cd meilisearch
          cargo build --release --locked

      - name: 验证 GLIBC 依赖
        run: |
          cd meilisearch/target/release
          ldd meilisearch | grep GLIBC_

      - name: 保存编译产物
        uses: actions/upload-artifact@v4
        with:
          name: meilisearch-v1.19.1-linux-amd64-rocky9
          path: meilisearch/target/release/meilisearch
          retention-days: 7
