name: Build Meilisearch v1.19.1 on Rocky Linux 9

on:
  workflow_dispatch:
    inputs:
      action:
        description: '触发类型'
        required: true
        default: 'build'
        enum: [build]

jobs:
  build-meilisearch:
    name: 编译 Meilisearch v1.19.1（Rocky Linux 9）
    container:
      image: litmusimage/rockylinux:9
    runs-on: ubuntu-latest

    steps:
      - name: 验证容器启动
        run: |
          ldd --version
          git --version
          curl --version
          gcc --version

      - name: 安装系统依赖
        run: |
          yum update -y
          yum install -y \
            git \
            curl \
            gcc \
            make \
            cmake3 \
            openssl-devel \
            zlib-devel \
            pkg-config \
            which
          sudo ln -sf /usr/bin/cmake3 /usr/bin/cmake

      - name: 安装 Rust 工具链
        uses: dtolnay/rust-toolchain@1.85
        with:
          toolchain: stable
          override: true
          components: rust-src, cargo, rustc-dev

      - name: 克隆并检出源码
        run: |
          git clone https://github.com/meilisearch/meilisearch.git
          cd meilisearch
          git checkout tags/v1.19.1

      - name: 配置编译环境
        run: |
          cd meilisearch
          export TARGET=x86_64-unknown-linux-gnu

      - name: 编译发布版
        run: |
          cd meilisearch
          cargo build --release --locked

      - name: 验证 GLIBC 依赖
        run: |
          cd meilisearch/target/release
          ldd meilisearch | grep GLIBC_

      - name: 保存编译产物（升级为 upload-artifact@v4）
        uses: actions/upload-artifact@v4  # 关键修改：替换为 v4
        with:
          name: meilisearch-v1.19.1-linux-amd64-rocky9  # 必填：工件名称
          path: meilisearch/target/release/meilisearch  # 必填：容器内文件路径（绝对或相对）
          retention-days: 7  # 可选：工件保留天数

      - name: 输出失败日志（可选）
        if: failure()
        run: |
          cat meilisearch/target/debug/build.log
