name: Build Meilisearch v1.19.1 on Rocky Linux 9

on:
  workflow_dispatch:
    inputs:
      action:
        description: '触发类型（仅 build）'
        required: true
        default: 'build'
        enum: [build]

jobs:
  build-meilisearch:
    name: 编译 Meilisearch v1.19.1（Rocky Linux 9）
    container:
      image: rockylinux/rockylinux:9
    runs-on: ubuntu-latest

    steps:
      ###########################
      # 步骤 1：安装基础工具（含 wget）
      ###########################
      - name: 安装基础工具（关键）
        run: |
          # 更新系统包索引（确保获取最新包信息）
          yum update -y
          
          # 安装 wget（用于下载 EPEL 仓库包）
          yum install -y wget
          
          # 安装其他基础工具（编译必需）
          yum install -y \
            git \
            gcc \
            make \
            cmake3 \
            openssl-devel \
            zlib-devel \
            which \
            yum-utils  # 包含 yum-config-manager

      ###########################
      # 步骤 2：安装 EPEL 仓库（依赖 wget）
      ###########################
      - name: 安装 EPEL 仓库
        run: |
          # 下载 EPEL 9 最新仓库包（使用已安装的 wget）
          wget -q https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
          
          # 安装 EPEL 仓库（生成 /etc/yum.repos.d/epel.repo）
          yum install -y ./epel-release-latest-9.noarch.rpm

      ###########################
      # 步骤 3：启用 EPEL 仓库并安装 pkgconf-pkg-config
      ###########################
      - name: 启用 EPEL 仓库并安装 pkgconf-pkg-config
        run: |
          # 启用 EPEL 仓库
          yum-config-manager --set-enabled epel
          
          # 安装 pkgconf-pkg-config（提供兼容的 pkg-config 工具）
          yum install -y pkgconf-pkg-config

      ###########################
      # 步骤 4：解决 curl 包冲突（可选，若仍冲突）
      ###########################
      - name: 解决 curl 包冲突（可选）
        run: |
          # 移除可能冲突的 curl-minimal（若已安装）
          yum remove -y curl-minimal || true
          
          # 安装完整版 curl（允许覆盖潜在冲突文件）
          yum install -y curl --allowerasing

      ###########################
      # 步骤 5：验证环境（关键检查）
      ###########################
      - name: 验证环境配置
        run: |
          # 检查 wget 是否安装成功
          wget --version  # 应输出 wget 版本信息（如 "GNU Wget 1.21.4"）
          
          # 检查 EPEL 仓库是否启用
          yum repolist enabled | grep epel  # 应输出 epel 仓库信息
          
          # 检查 pkg-config 是否可用
          pkg-config --version
          
          # 检查其他基础工具（git、curl、gcc 等）
          git --version
          curl --version
          gcc --version

      ###########################
      # 后续步骤（Rust 安装、编译等）保持不变...
      ###########################
      - name: 安装 Rust 工具链
        uses: dtolnay/rust-toolchain@1.85
        with:
          toolchain: stable
          override: true
          components: rust-src, cargo, rustc-dev

      - name: 克隆并检出源码
        run: |
          git clone https://github.com/meilisearch/meilisearch.git
          cd meilisearch
          git checkout tags/v1.19.1

      - name: 配置编译环境
        run: |
          cd meilisearch
          export TARGET=x86_64-unknown-linux-gnu

      - name: 编译发布版
        run: |
          cd meilisearch
          cargo build --release --locked

      - name: 验证 GLIBC 依赖
        run: |
          cd meilisearch/target/release
          ldd meilisearch | grep GLIBC_

      - name: 保存编译产物
        uses: actions/upload-artifact@v4
        with:
          name: meilisearch-v1.19.1-linux-amd64-rocky9
          path: meilisearch/target/release/meilisearch
          retention-days: 7
