name: Build from Release Tag v1.19

on:
  workflow_dispatch:
    inputs:
      # 移除分支选择，改为固定触发
      action:
        description: '触发类型'
        required: true
        default: 'build'
        enum: [build, dry-run]

jobs:
  build-linux-x86_64:
    name: 编译 Linux x86_64 二进制
    runs-on: rockylinux:9
    steps:
      - name: 检出指定标签
        uses: actions/checkout@v4
        with:
          repository: meilisearch/meilisearch
          ref: refs/tags/v1.19.1  # 直接指定标签引用

      - name: 安装基础依赖
        run: |
          sudo dnf install -y curl git build-essential cmake3
          sudo ln -s /usr/bin/cmake3 /usr/bin/cmake

      - name: 配置 Rust 工具链
        uses: dtolnay/rust-toolchain@1.85
        with:
          toolchain: stable
          override: true

      - name: 设置交叉编译环境
        run: |
          echo '[target.x86_64-unknown-linux-gnu]' >> ~/.cargo/config
          echo 'linker = "gcc"' >> ~/.cargo/config

      - name: 编译发布版
        run: cargo build --release --locked

      - name: 保存构建产物
        uses: actions/upload-artifact@v3
        with:
          name: meilisearch-linux-x86_64
          path: target/release/meilisearch

      - name: 上传到 Release（仅正式构建）
        if: github.event_name == 'release' && inputs.action == 'build'
        uses: svenstaro/upload-release-action@2.11.2
        with:
          repo_token: ${{ secrets.MEILI_BOT_GH_PAT }}
          file: target/release/meilisearch
          asset_name: meilisearch-linux-x86_64
          tag: v1.19  # 强制绑定标签版本
