name: Build Zed IDE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: |
        choco install dotnetcore-sdk --version=8.0 -y
        choco install visualstudio2019buildtools -y
        choco install rustup.install -y
    - name: Install and Setup Rust
      shell: powershell
      run: |
        rustup update
        rustup default stable
        rustup target add wasm32-unknown-unknown
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0' # Specify the .NET Core SDK version you need

    #- name: Set up Node.js
    #  uses: actions/setup-node@v4
    #  with:
    #    node-version: '20'

    - name: Clone and Build Zed IDE
      run: |
        # Clone repo
        git clone -b v0.141.2 --depth=1 https://github.com/zed-industries/zed
        cd zed
        # Install npm dependencies
        #npm install
        # Build with npm
        #npm run build
        # Build with Cargo
        cargo build --release
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: zed-ide-build
        path: zed/target/release/zed.exe
